### ISSUE TITLE
Add new map zagorsk big city

### ISSUE THREAD

**Issue by PR2403** [jetelain/GameMapStorage.Arma3#1]
Hi, 
Can you add a map on atlas.plan-ops.fr / maps.plan-ops.fr ?
Workshop link: [[Link to the workshop]](https://steamcommunity.com/sharedfiles/filedetails/?id=3215347955)
We Transfer Link: https://we.tl/t-4BJuVxrmwj

**Comment by jetelain** [comment]
Hi, it's available on the new atlas : https://atlas.plan-ops.fr/maps/arma3/zagor_zagorsk_big_city
it will be available on maps and ctab in few hours
