### ISSUE TITLE
Add new maps Summa, Maksniemi, 41-Ruegen

### ISSUE THREAD

**Issue by z3r03nna** [jetelain/GameMapStorage.Arma3#4]
Hi, 
Can you add the following maps on atlas.plan-ops.fr / maps.plan-ops.fr ?

Maksniemi:
Workshop: https://steamcommunity.com/sharedfiles/filedetails/?id=2696444371

Summa: https://steamcommunity.com/sharedfiles/filedetails/?id=1598087521
(2 Variants)

Ruegen: https://steamcommunity.com/sharedfiles/filedetails/?id=835257174
(2 Variants)

Download:
https://nextcloud.itdienstleister.net/s/bpzGDw4P8mrqbMJ

Thanks

**Comment by z3r03nna** [comment]
Just seeing right now that Ruegen is already uploaded. So forget about that :)

**Comment by jetelain** [comment]
Hi,

Maps have been added to the atlas, it will be available in few hours on maps.plan-ops.fr

https://atlas.plan-ops.fr/maps/arma3/maksniemi
https://atlas.plan-ops.fr/maps/arma3/tem_summa
https://atlas.plan-ops.fr/maps/arma3/tem_summawcup
