### ISSUE TITLE
Map Request: Entropy

### ISSUE THREAD

**Issue by Aeicos01** [jetelain/GameMapStorage.Arma3#5]
Hiiiiiiii, 
Can you add a map on atlas.plan-ops.fr / maps.plan-ops.fr ?
Workshop link: https://steamcommunity.com/sharedfiles/filedetails/?id=3268711459&searchtext=entropy

**Comment by jetelain** [comment]
Hi, I'm sorry map is too small, and cannot be exported right now (same issue than Sandstorm from OPTRE, https://github.com/jetelain/Arma3Map/issues/88)

**Comment by jetelain** [comment]
Hi, good news, basic export have worked : https://atlas.plan-ops.fr/maps/arma3/entropy
but it wont be possible to have a better resolution

**Comment by jetelain** [comment]
Hi, it's available on maps and ctab
